<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ PlayMoreSounds - A Minecraft plugin that manages and plays sounds.
  ~ Copyright (C) 2023-2026 Christiano Rangel
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.epicnicity322</groupId>
    <artifactId>PlayMoreSounds</artifactId>
    <packaging>pom</packaging>
    <name>PlayMoreSounds</name>
    <modules>
        <module>bukkit</module>
        <module>core</module>
        <module>sponge</module>
    </modules>
    <version>6.0</version>
    <url>https://github.com/chrisrnj/PlayMoreSounds/</url>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/chrisrnj/PlayMoreSounds/issues</url>
    </issueManagement>

    <licenses>
        <license>
            <name>GPL-v3.0</name>
            <url>https://www.gnu.org/licenses/gpl-3.0.txt</url>
        </license>
    </licenses>

    <properties>
        <bstats-version>3.1.0</bstats-version>
        <maven-shade-plugin.version>3.6.1</maven-shade-plugin.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <finalName>${project.name}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.chrisrnj</groupId>
            <artifactId>EpicPluginLib</artifactId>
            <version>014345df2a</version>
            <scope>provided</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/io.soabase.record-builder/record-builder-core -->
        <dependency>
            <groupId>io.soabase.record-builder</groupId>
            <artifactId>record-builder-core</artifactId>
            <version>51</version>
            <scope>compile</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.jetbrains/annotations -->
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.0.2-1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>